services:
  backend:
    build: ./backend
    environment:
      - PORT=4000
      - THRONES_API_BASE=https://thronesapi.com
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BFF_BASE_URL: http://localhost:4000
    ports:
      - "3000:80"
    depends_on:
      - backend
